### ISSUE TITLE
写真の著作権まわりの調査

### ISSUE THREAD

**Issue by pine0619** [pine0619/enpit_omusubi#12]

**Comment by pine0619** [comment]
インスタの写真の著作権

**Comment by pine0619** [comment]
インスタの写真の著作権

**Comment by e185755** [comment]
インスタ公式は埋め込みに対して著作権関連の情報は載せていない（API事態そういったことはサポートされてないかも）
実際に質問に対して「埋め込み機能は画像の使用を許可するものではない。許可を取った上で使うように。」と回答しているらしい。
利用規約としてはサポートされてないが、裁判の判決は必ずしも負けと言うわけでもなく、サーバーテストの観点からアメリカでは著作権侵害ではないとした判決が出ている事例もある。
ただし基本的に許可のない埋め込みは著作権侵害とみて動いた方が良さそう。

ちなみに今後埋め込み可能・不可能のチェックを投稿側で付ける機能が実装される可能性もあり、そうなった場合は著作権を気にせず使えるかもしれない。
あとTwitterは埋め込みは引用であると利用規約に書いてあるのでOKらしい。

参考リンク
https://homepage-reborn.com/2020/06/10/instagramの画像埋め込み機能は著作権侵害になる？！facebook/
https://cameragakari.com/instagram-embed-quote/#st-toc-h-3
